// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/nuttchai/go-rest/internal/handler"
	"github.com/nuttchai/go-rest/internal/handler/interface"
	"github.com/nuttchai/go-rest/internal/repository"
	"github.com/nuttchai/go-rest/internal/repository/interface"
	"github.com/nuttchai/go-rest/internal/service"
	"github.com/nuttchai/go-rest/internal/service/interface"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

//go:generate go run github.com/google/wire/cmd/wire
func InitializeApp() (*App, func(), error) {
	tapiConfig, err := ProvideAPIConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDatabase(tapiConfig)
	if err != nil {
		return nil, nil, err
	}
	tSampleRepository := repository.NewSampleRepository(db)
	tSampleService := service.NewSampleService(tSampleRepository)
	tUserRepository := repository.NewUserRepository(db)
	tUserService := service.NewUserService(tUserRepository)
	tSampleHandler := handler.NewSampleHandler(tSampleService, tUserService)
	tUserHandler := handler.NewUserHandler(tUserService)
	echo := ProvideServer(tSampleHandler, tUserHandler)
	app := NewApp(echo, tapiConfig)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewSampleRepository, wire.Bind(new(irepository.ISampleRepository), new(*repository.TSampleRepository)), repository.NewUserRepository, wire.Bind(new(irepository.IUserRepository), new(*repository.TUserRepository)))

var serviceSet = wire.NewSet(service.NewSampleService, wire.Bind(new(iservice.ISampleService), new(*service.TSampleService)), service.NewUserService, wire.Bind(new(iservice.IUserService), new(*service.TUserService)))

var handlerSet = wire.NewSet(handler.NewSampleHandler, wire.Bind(new(ihandler.ISampleHandler), new(*handler.TSampleHandler)), handler.NewUserHandler, wire.Bind(new(ihandler.IUserHandler), new(*handler.TUserHandler)))
